{
 "title": "Demo04 Dashboard",
 "time": { "from": "now-4s", "to": "now-1s" },
 "panels": [
  {
   "title": "Single Value Stat",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() AS \"time\",\n  'Percent Complete' AS \"metric\",\n  93.2 AS \"value\""
    }
   ]
  },
  {
   "title": "Single Value Gauge",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() AS \"time\",\n  'Percent Complete' AS \"metric\",\n  93.2 AS \"value\""
    }
   ]
  },
  {
   "title": "Single Value Bar",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() AS \"time\",\n  'Percent Complete' AS \"metric\",\n  93.2 AS \"value\""
    }
   ]
  },
  {
   "title": "Multivalue Stat",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time, metric, value\nFROM\n  (VALUES\n    (NOW(), 'metric1', 23),\n    (NOW(), 'metric2', 5.14),\n    (NOW(), 'metric3', 2.71))\n  AS x(time, metric, value)\n"
    }
   ]
  },
  {
   "title": "Multivalue Gauge",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time, metric, value\nFROM\n  (VALUES\n    (NOW(), 'metric1', 23),\n    (NOW(), 'metric2', 5.14),\n    (NOW(), 'metric3', 2.71))\n  AS x(time, metric, value)\n"
    }
   ]
  },
  {
   "title": "Multivalue Bar",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time, metric, value\nFROM\n  (VALUES\n    (NOW(), 'metric1', 23),\n    (NOW(), 'metric2', 5.14),\n    (NOW(), 'metric3', 2.71))\n  AS x(time, metric, value)\n"
    }
   ]
  },
  {
   "title": "Multivalue Table",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  id as \"Id\", color as \"Color\", meaning as \"Description\"\nFROM\n  (VALUES\n    (1, 'green', 'all tests passed'),\n    (2, 'yellow', 'some tests failed but all critical tests passed'),\n    (3, 'red', 'at least one critical test failed'))\n  AS x(id, color, meaning)"
    }
   ]
  },
  {
   "title": "Heatmap",
   "type": "heatmap",
   "description": "Example of a simple heat map.",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  time, metric, value\nFROM\n  (VALUES\n    (NOW(), 'metric1', 1.0),\n    (NOW(), 'metric1', 1.0),\n    (NOW(), 'metric1', 1.0),\n    (NOW(), 'metric1', 1.0),\n    (NOW(), 'metric1', 1.0),\n    (NOW(), 'metric1', 1.0),\n    (NOW(), 'metric1', 1.0),\n    \n    (NOW() - INTERVAL '1 SECOND', 'metric1', 1.0),\n    (NOW() - INTERVAL '1 SECOND', 'metric1', 1.0),\n    (NOW() - INTERVAL '1 SECOND', 'metric1', 1.0),\n    (NOW() - INTERVAL '1 SECOND', 'metric1', 1.0),\n    (NOW() - INTERVAL '1 SECOND', 'metric1', 1.0),\n    (NOW() - INTERVAL '1 SECOND', 'metric1', 1.0),\n\n    (NOW() - INTERVAL '2 SECOND', 'metric1', 1.0),\n    (NOW() - INTERVAL '2 SECOND', 'metric1', 1.0),\n    (NOW() - INTERVAL '2 SECOND', 'metric1', 1.0),\n    (NOW() - INTERVAL '2 SECOND', 'metric1', 1.0),\n    (NOW() - INTERVAL '2 SECOND', 'metric1', 1.0),\n    (NOW() - INTERVAL '2 SECOND', 'metric1', 1.0),\n    (NOW() - INTERVAL '2 SECOND', 'metric1', 1.0),\n    (NOW() - INTERVAL '2 SECOND', 'metric1', 1.0),\n    (NOW() - INTERVAL '2 SECOND', 'metric1', 1.0),\n    (NOW() - INTERVAL '2 SECOND', 'metric1', 1.0),\n\n    (NOW() - INTERVAL '3 SECOND', 'metric1', 1.0),\n    (NOW() - INTERVAL '3 SECOND', 'metric1', 1.0),\n    (NOW() - INTERVAL '3 SECOND', 'metric1', 1.0),\n    (NOW() - INTERVAL '3 SECOND', 'metric1', 1.0),\n    \n    (NOW() - INTERVAL '4 SECOND', 'metric1', 1.0),\n    (NOW() - INTERVAL '4 SECOND', 'metric1', 1.0),\n    (NOW() - INTERVAL '4 SECOND', 'metric1', 1.0))\n  AS x(time, metric, value)"
    },
    {
     "rawSql": "SELECT\n  time, metric, value\nFROM\n  (VALUES\n    (NOW(), 'metric2', 2.0),\n    (NOW(), 'metric2', 2.0),\n    (NOW(), 'metric2', 2.0),\n    (NOW(), 'metric2', 2.0),\n    (NOW(), 'metric2', 2.0),\n    (NOW(), 'metric2', 2.0),\n    (NOW(), 'metric2', 2.0),\n    (NOW(), 'metric2', 2.0),\n    (NOW(), 'metric2', 2.0),\n    (NOW(), 'metric2', 2.0),\n\n    (NOW() - INTERVAL '1 SECOND', 'metric2', 2.0),\n    (NOW() - INTERVAL '1 SECOND', 'metric2', 2.0),\n    (NOW() - INTERVAL '1 SECOND', 'metric2', 2.0),\n    (NOW() - INTERVAL '1 SECOND', 'metric2', 2.0),\n    (NOW() - INTERVAL '1 SECOND', 'metric2', 2.0),\n    (NOW() - INTERVAL '1 SECOND', 'metric2', 2.0),\n\n    (NOW() - INTERVAL '2 SECOND', 'metric2', 2.0),\n    (NOW() - INTERVAL '2 SECOND', 'metric2', 2.0),\n    (NOW() - INTERVAL '2 SECOND', 'metric2', 2.0),\n    (NOW() - INTERVAL '2 SECOND', 'metric2', 2.0),\n    (NOW() - INTERVAL '2 SECOND', 'metric2', 2.0),\n\n    (NOW() - INTERVAL '3 SECOND', 'metric2', 2.0),\n    (NOW() - INTERVAL '3 SECOND', 'metric2', 2.0),\n    (NOW() - INTERVAL '3 SECOND', 'metric2', 2.0),\n    (NOW() - INTERVAL '3 SECOND', 'metric2', 2.0),\n    (NOW() - INTERVAL '3 SECOND', 'metric2', 2.0),\n    (NOW() - INTERVAL '3 SECOND', 'metric2', 2.0),\n\n    (NOW() - INTERVAL '4 SECOND', 'metric2', 2.0),\n    (NOW() - INTERVAL '4 SECOND', 'metric2', 2.0),\n    (NOW() - INTERVAL '4 SECOND', 'metric2', 2.0),\n    (NOW() - INTERVAL '4 SECOND', 'metric2', 2.0),\n    (NOW() - INTERVAL '4 SECOND', 'metric2', 2.0),\n    (NOW() - INTERVAL '4 SECOND', 'metric2', 2.0),\n    (NOW() - INTERVAL '4 SECOND', 'metric2', 2.0))\n  AS x(time, metric, value)\n"
    },
    {
     "rawSql": "SELECT\n  time, metric, value\nFROM\n  (VALUES\n    (NOW(), 'metric3', 3.0),\n    (NOW(), 'metric3', 3.0),\n    (NOW(), 'metric3', 3.0),\n    (NOW(), 'metric3', 3.0),\n    (NOW(), 'metric3', 3.0),\n    (NOW(), 'metric3', 3.0),\n    (NOW(), 'metric3', 3.0),\n    (NOW(), 'metric3', 3.0),\n    (NOW(), 'metric3', 3.0),\n    (NOW(), 'metric3', 3.0),\n    \n    (NOW() - INTERVAL '1 SECOND', 'metric3', 3.0),\n    (NOW() - INTERVAL '1 SECOND', 'metric3', 3.0),\n    (NOW() - INTERVAL '1 SECOND', 'metric3', 3.0),\n    (NOW() - INTERVAL '1 SECOND', 'metric3', 3.0),\n    (NOW() - INTERVAL '1 SECOND', 'metric3', 3.0),\n    (NOW() - INTERVAL '1 SECOND', 'metric3', 3.0),\n    (NOW() - INTERVAL '1 SECOND', 'metric3', 3.0),\n    (NOW() - INTERVAL '1 SECOND', 'metric3', 3.0),\n    (NOW() - INTERVAL '1 SECOND', 'metric3', 3.0),\n\n    (NOW() - INTERVAL '2 SECOND', 'metric3', 3.0),\n    (NOW() - INTERVAL '2 SECOND', 'metric3', 3.0),\n    (NOW() - INTERVAL '2 SECOND', 'metric3', 3.0),\n    (NOW() - INTERVAL '2 SECOND', 'metric3', 3.0),\n    (NOW() - INTERVAL '2 SECOND', 'metric3', 3.0),\n    (NOW() - INTERVAL '2 SECOND', 'metric3', 3.0),\n    (NOW() - INTERVAL '2 SECOND', 'metric3', 3.0),\n    (NOW() - INTERVAL '2 SECOND', 'metric3', 3.0),\n\n    (NOW() - INTERVAL '3 SECOND', 'metric3', 3.0),\n    (NOW() - INTERVAL '3 SECOND', 'metric3', 3.0),\n    (NOW() - INTERVAL '3 SECOND', 'metric3', 3.0),\n    (NOW() - INTERVAL '3 SECOND', 'metric3', 3.0),\n    (NOW() - INTERVAL '3 SECOND', 'metric3', 3.0),\n    (NOW() - INTERVAL '3 SECOND', 'metric3', 3.0),\n    (NOW() - INTERVAL '3 SECOND', 'metric3', 3.0),\n\n    (NOW() - INTERVAL '4 SECOND', 'metric3', 3.0),\n    (NOW() - INTERVAL '4 SECOND', 'metric3', 3.0),\n    (NOW() - INTERVAL '4 SECOND', 'metric3', 3.0),\n    (NOW() - INTERVAL '4 SECOND', 'metric3', 3.0),\n    (NOW() - INTERVAL '4 SECOND', 'metric3', 3.0),\n    (NOW() - INTERVAL '4 SECOND', 'metric3', 3.0))\n  AS x(time, metric, value)"
    },
    {
     "rawSql": "SELECT\n  time, metric, value\nFROM\n  (VALUES\n    (NOW(), 'metric4', 4))\n  AS x(time, metric, value)"
    }
   ]
  }
 ]
}