{
 "title": "Demo03 Dashboard",
 "time": { "from": "2020-09-01T07:00:00.000Z", "to": "2020-09-09T06:59:59.000Z" },
 "panels": [
  {
   "title": "proc01",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  tstamp AS \"time\",\n  metric AS metric,\n  value\nFROM ts1\nWHERE\n  $__timeFilter(tstamp) AND metric = 'proc01'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "proc02",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  tstamp AS \"time\",\n  metric AS metric,\n  value\nFROM ts1\nWHERE\n  $__timeFilter(tstamp) AND metric = 'proc02'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "proc03",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  tstamp AS \"time\",\n  metric AS metric,\n  value\nFROM ts1\nWHERE\n  $__timeFilter(tstamp) AND metric = 'proc03'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "proc04",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  tstamp AS \"time\",\n  metric AS metric,\n  value\nFROM ts1\nWHERE\n  $__timeFilter(tstamp) AND metric = 'proc04'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "proc05",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  tstamp AS \"time\",\n  metric AS metric,\n  value\nFROM ts1\nWHERE\n  $__timeFilter(tstamp) AND metric = 'proc05'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "proc06",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  tstamp AS \"time\",\n  metric AS metric,\n  value\nFROM ts1\nWHERE\n  $__timeFilter(tstamp) AND metric = 'proc06'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "proc07",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  tstamp AS \"time\",\n  metric AS metric,\n  value\nFROM ts1\nWHERE\n  $__timeFilter(tstamp) AND metric = 'proc07'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "proc08",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  tstamp AS \"time\",\n  metric AS metric,\n  value\nFROM ts1\nWHERE\n  $__timeFilter(tstamp) AND metric = 'proc08'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "proc09",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  tstamp AS \"time\",\n  metric AS metric,\n  value\nFROM ts1\nWHERE\n  $__timeFilter(tstamp) AND metric = 'proc09'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "proc10",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  tstamp AS \"time\",\n  metric AS metric,\n  value\nFROM ts1\nWHERE\n  $__timeFilter(tstamp) AND metric = 'proc10'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Chart",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  tstamp AS \"time\",\n  metric AS metric,\n  value\nFROM ts1\nWHERE\n  $__timeFilter(tstamp)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Another View",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 9, "x": 11, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  tstamp AS \"time\",\n  metric AS metric,\n  value\nFROM ts1\nWHERE\n  $__timeFilter(tstamp) AND metric = 'proc01'\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  tstamp AS \"time\",\n  metric AS metric,\n  value\nFROM ts1\nWHERE\n  $__timeFilter(tstamp) AND metric = 'proc02'\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  tstamp AS \"time\",\n  metric AS metric,\n  value\nFROM ts1\nWHERE\n  $__timeFilter(tstamp) AND metric = 'proc03'\nORDER BY 1,2\n"
    },
    {
     "rawSql": "SELECT\n  tstamp AS \"time\",\n  metric AS metric,\n  value\nFROM ts1\nWHERE\n  $__timeFilter(tstamp) AND metric = 'proc04'\nORDER BY 1,2\n"
    },
    {
     "rawSql": "SELECT\n  tstamp AS \"time\",\n  metric AS metric,\n  value\nFROM ts1\nWHERE\n  $__timeFilter(tstamp) AND metric = 'proc05'\nORDER BY 1,2\n"
    }
   ]
  }
 ]
}