{
 "title": "Dem02 Dashboard",
 "time": { "from": "2020-03-01T08:00:00.000Z", "to": "2020-08-01T07:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "country",
    "query": "select distinct country from all_weekly_excess_deaths_view order by country"
   },
   {
    "name": "region",
    "query": "select distinct region from all_weekly_excess_deaths_view where country = '$country' order by region"
   }
  ]
 },
 "panels": [
  {
   "title": "UnCounted",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  covid_deaths - greatest(least(covid_deaths, total_deaths - expected_deaths), 0) as extra\nFROM\n  all_weekly_excess_deaths_view\nWHERE\n  country = '$country' and region = '$region'\nORDER BY\n  all_weekly_excess_deaths_view.time asc\n"
    }
   ]
  },
  {
   "title": "Expected vs Actual COVID-19 Deaths - $country, $region",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, '1w'),\n  least(non_covid_deaths, expected_deaths) as \"correctly reported non-covid\",\n  greatest(least(covid_deaths, total_deaths - expected_deaths), 0) as \"correctly reported covid\",\n  non_covid_deaths - least(non_covid_deaths, expected_deaths) as \"non-covid cases incorrectly reported as covid\",\n  covid_deaths - greatest(least(covid_deaths, total_deaths - expected_deaths), 0) as \"covid cases incorrectly reported as non-covid\",\n  'weekly:' as metric\nFROM\n  all_weekly_excess_deaths_view\nWHERE\n  $__timeFilter(time) and country = '$country' and region = '$region'\nGROUP BY\n  all_weekly_excess_deaths_view.time,\n  all_weekly_excess_deaths_view.total_deaths,\n  all_weekly_excess_deaths_view.expected_deaths,\n  all_weekly_excess_deaths_view.non_covid_deaths,\n  all_weekly_excess_deaths_view.covid_deaths\nORDER BY\n  all_weekly_excess_deaths_view.time,\n  all_weekly_excess_deaths_view.total_deaths,\n  all_weekly_excess_deaths_view.expected_deaths,\n  all_weekly_excess_deaths_view.non_covid_deaths, \n  all_weekly_excess_deaths_view.covid_deaths ASC\n"
    }
   ]
  },
  {
   "title": "Raw Data",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  time as \"Time\",\n  least(non_covid_deaths, expected_deaths) as \"Non-Covid\",\n  greatest(least(covid_deaths, total_deaths - expected_deaths), 0) as \"Covid\",\n  non_covid_deaths - least(non_covid_deaths, expected_deaths) as \"Uncounted Non-Covid\",\n  covid_deaths - greatest(least(covid_deaths, total_deaths - expected_deaths), 0) as \"Uncounted Covid\"\nFROM\n  all_weekly_excess_deaths_view\nWHERE\n  $__timeFilter(time) and country = '$country' and region = '$region'\nGROUP BY\n  all_weekly_excess_deaths_view.time,\n  all_weekly_excess_deaths_view.total_deaths,\n  all_weekly_excess_deaths_view.expected_deaths,\n  all_weekly_excess_deaths_view.non_covid_deaths,\n  all_weekly_excess_deaths_view.covid_deaths\nORDER BY\n  all_weekly_excess_deaths_view.time,\n  all_weekly_excess_deaths_view.total_deaths,\n  all_weekly_excess_deaths_view.expected_deaths,\n  all_weekly_excess_deaths_view.non_covid_deaths, \n  all_weekly_excess_deaths_view.covid_deaths ASC\n"
    }
   ]
  }
 ]
}