# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or
# pull request events but only for the master branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as
    # part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your
      # job can access it
      - uses: actions/checkout@v2

      - name: 'Set up Python 3.8'
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python
          # version
          python-version: '3.8'

      - name: 'Install pipenv'
        run: pip install pipenv

      - name: 'Build and test'
        run: make

      - name: 'Archive code coverage results'
        uses: actions/upload-artifact@v2
        with:
          name: 'code-coverage-report'
          path: test/htmlcov

      - name: 'Archive test results'
        uses: actions/upload-artifact@v2
        with:
          name: 'test-report'
          path: |
            test/report.html
            test/assets
